### ISSUE TITLE
Update injector to use a bundle manifest.json

### ISSUE THREAD

**Issue by adslaton** [cnnlabs/injectorjs#17]
Currently a webpackassets object is expected to be defined. In lieu of doing this, a bundle manifest file should be used to track versions. An example being http://registry.dev.api.cnn.io/bundles/injectorjs/manifest.0.7.0.json

The required structure of the manifest should be:

```
[
    {
        name: "relative/path/to/resource/name.extension",
        chunkNames: [
            "resource"
        ]
    }
]
```

**Comment by ghost** [comment]
Do you want me to work on this?

**Comment by adslaton** [comment]
Each bundle should define a manifest in the root of it's directory.

Directory

```
/bundles
    /<bundle-name>
        /manifest.<version>.json
```

We will likely need to build a logic layer in the registry that will require the bundle name, version, and reouse to be passed. The logic would use that info to find the related manifest in order to pass back the proper resource file.

**Comment by adslaton** [comment]
This was addressed with the creation of the logic layer in the registry.
