### ISSUE TITLE
Add a ready state property to the injector.

### ISSUE THREAD

**Issue by martytheparty** [cnnlabs/injectorjs#32]
Add a ready state property to the injector.  The ready state property should mimic https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState.  Thanks.

**Comment by martytheparty** [comment]
I am starting work on this issue.

**Comment by ghost** [comment]
are you still working on this or do you want me to do it?

**Comment by martytheparty** [comment]
I just created a PR for this issue.

**Comment by adslaton** [comment]
Addressed in https://github.com/cnnlabs/injectorjs/pull/34
